name: "Inclusion / Exclusion Submissions"
description: "Submit a BBMM inclusion or exclusion JSON file"
title: "[Inclusion/Exclusion] "
category: "Inclusion/Exclusion submissions"
labels:
  - "inclusion-exclusion"

body:
  - type: markdown
    attributes:
      value: |
        ## Submit a BBMM Inclusion / Exclusion File

        Please attach your `.json` file to this discussion before posting:
        - Drag and drop the file into the editor, or use the attachment button.
        - The JSON must include:
          - `schemaVersion`
          - `target`
          - `targetVersion`
          - `foundryVersion`
          - `entries`

        If no `.json` file is attached, the validator workflow will not pass.

  - type: dropdown
    id: "fileType"
    attributes:
      label: "File Type"
      description: "Is this an inclusions file or exclusions file?"
      options:
        - "inclusions"
        - "exclusions"
    validations:
      required: true

  - type: input
    id: "target"
    attributes:
      label: "Target Namespace (Module/System ID)"
      description: "Example: pf2e-workbench or bbmm"
      placeholder: "pf2e-workbench"
    validations:
      required: true

  - type: input
    id: "targetVersion"
    attributes:
      label: "Target Version"
      description: "Version of the module/system this file was created for."
      placeholder: "6.5.3"
    validations:
      required: true

  - type: input
    id: "foundryVersion"
    attributes:
      label: "Foundry Version"
      description: "Foundry version used when creating/testing this file."
      placeholder: "13.3.0"
    validations:
      required: true

  - type: textarea
    id: "description"
    attributes:
      label: "Description (Optional)"
      description: "Briefly describe what this inclusion/exclusion file covers."
      placeholder: "Includes all hidden automation-related settings for PF2e Workbench."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Required: Attach Your JSON File

        Make sure your `.json` file is attached to this discussion.
        The validator will automatically check it when posted or edited.

  - type: textarea
    id: "links"
    attributes:
      label: "Related Links (Optional)"
      description: "Optional links to the module/system page or documentation."
      placeholder: |
        - Module page: ...
        - Documentation: ...
    validations:
      required: false
