name: Inclusion/Exclusion advice
description: Get guidance on which settings should be included or excluded in a preset/export (with caution around hidden/state data).
title: "[Advice] Briefly describe what you need"
labels:
  - advice
  - inclusion-exclusion
assignees:
  - thejoester
body:
  - type: markdown
    attributes:
      value: |
        Thanks! This form helps us recommend **what to include/exclude** in presets and exports.
        - Avoid sharing secrets (API keys, license keys).
        - If possible, include screenshots of relevant settings pages.
        - BBMM avoids auto-saving **live “state” data** to prevent overwriting active sessions; we’ll focus on stable **configuration**.

  - type: dropdown
    id: context
    attributes:
      label: Primary context
      description: What situation are you preparing for?
      options:
        - Preset export to reuse later
        - World-to-world migration
        - New world bootstrap (baseline setup)
        - Troubleshooting a problematic setup
        - Other (explain below)
    validations:
      required: true

  - type: textarea
    id: world_system_versions
    attributes:
      label: World/System/Versions
      description: Include Foundry version, system(s), BBMM version, and any other critical version info. 
      placeholder: |
        Foundry: v12.xx (or v13.xx)
        System: PF2e 5.xx
        BBMM: 0.x.x
        OS/Browser (if relevant):

  - type: textarea
    id: modules
    attributes:
      label: Modules and hidden keys to evaluate (names + package IDs if possible)
      description: List the modules and settings you are seeking advice on. Include the module, key and value (if no private data is included). 

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmations
      options:
        - label: I will not include secrets (license keys, API tokens, passwords) in this issue
          required: true
